# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    ##branches: [ main ]
    types: [edited, labeled, opened, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Pull Request Labels
  # You may pin to the exact commit or the version.
  # uses: NathanielHill/check-pr-label-action@c55b3337f3234b6755a175fa255380726a4a6e98
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'M.**'
      
      - name: Check title
  # Check that the title has a format "[key-number]" "Description"
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '\[\w{2,3}-\d{1,}\].*' # Regex the title should match.

          prefix_case_sensitive: false # title prefix are case insensitive
          github_token: ${{ github.token }} # Default: ${{ github.token }}
