name: Block Merge on Unreviewed PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-unreviewed-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Check for Unreviewed PRs
      run: |
          # Get username from the current PR
          PR_CREATOR=$(jq -r .pull_request.user.login < $GITHUB_EVENT_PATH)

          # Fetch PRs assigned to the user using GitHub API
          PRS_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&assignee=$PR_CREATOR")

          # Process each PR
          echo "$PRS_JSON" | jq -c '.[]' | while read -r pr; do
            PR_NUMBER=$(echo "$pr" | jq -r '.number')
            PR_TITLE=$(echo "$pr" | jq -r '.title')

            # Check if the PR has been reviewed by the PR creator
            REVIEWS_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews")

            # Check for reviews done by the PR creator
            CREATOR_REVIEWS_COUNT=$(echo "$REVIEWS_JSON" | jq '[.[] | select(.user.login == "'$PR_CREATOR'")] | length')

            # Check if there are no reviews by the PR creator
            if [[ $CREATOR_REVIEWS_COUNT -eq 0 ]]; then
              echo "Blocking merge due to PR #${PR_NUMBER}: '${PR_TITLE}' not reviewed by the assignee."
              exit 1
            fi
          done
