name: Label PRs

on:
  pull_request:
  types: [opened, labeled, unlabeled, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"