# This is a basic workflow to help you get started with Actions

name: Check pull request conventions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    ##branches: [ main ]
    types: [edited, opened, labeled, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check Pull Request Task type Label
        # Check that the pull request has at least one label of type "T.*"
        uses: germanalvarez8/verify-pr-label-action@master
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'M. Activity Stream, M. Administración, M.Billing, M. Comisiones, M. Configuraciones de Telefonía, M. Consultas de ordenes, M. Deploy, M. Dialer, M. Drivers APP, M. Drivers, M. Edición de lead, M. Edición de orden, M. Facebook API, M. FollowUp, M. Grabaciones, M. Ingreso de orden, M. Invoices, M. Lead express, M. Merchants, M. Mi dids, M. Mis campañas, M. Mis ordenes, M. Pre leads, M. Reportes de leads, M. Reportes de ordenes, M. Robots, M. Shipping, M. Sincronización, M. Telinta API, M. Usuarios, M. Vendedores, M. Verificaciones, M. Webphone, M. WhatsApp, T. Actualización de valores, T. Fix código, T. Fix visual, T. Mejora de código, T. Mejora visual T. Nueva funcionalidad, T. Nueva sección'
          regex: 'M\..*,T\..*'

      - name: Check title conventions
        # Check that the title has a format "[key-number]" "Description"
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '\[\w{2,3}-\d{1,}\]\s-\s.*' # Regex the title should match.

          prefix_case_sensitive: false # title prefix are case insensitive
          github_token: ${{ github.token }} # Default: ${{ github.token }}
